#include "ChsOpenGL.h"

//ogl extension

#if defined(CHS_PLATFORM_ANDROID)

PFNGLGENVERTEXARRAYSOESPROC  glGenVertexArraysOES;
PFNGLBINDVERTEXARRAYOESPROC  glBindVertexArrayOES;
PFNGLDELETEVERTEXARRAYSOESPROC  glDeleteVertexArraysOES;

#endif